/* Игровая логика без зависимости от страницы: два игрока или напарник на телефоне. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LoveQuestCore=api;})(typeof window==='undefined'?this:window,function(){
  'use strict';
  const W=960,H=540,clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
  const LEVELS=[
    {name:'Гробница двух сердец',short:'Гробница',goal:'Победите скелетов, найдите ключ и доберитесь до выхода.',intro:'Олег: «Главное — держаться вместе. Даже если соседи немного костлявые».',outro:'Настя: «Кажется, свидание вышло немного необычным».',achievement:'Из гробницы — вместе',background:0,total:7,type:'skeleton'},
    {name:'А медведь был против',short:'Медведь',goal:'Уклоняйтесь от красного круга и победите медведя.',intro:'Настя: «Олег… Это точно не тот мишка, которого можно обнять?»',outro:'Олег: «Медведя победили. А вот что там светится над нами?»',achievement:'Злые медведи',background:1,total:1,type:'bear'},
    {name:'Такси до звёзд',short:'НЛО',goal:'Сбейте 12 дронов. Двигайтесь и стреляйте вперёд.',intro:'Пуф! Каждому по тарелке. Следующая остановка — где-нибудь подальше от медведей.',outro:'Настя: «Даже инопланетяне не смогли испортить нам свидание».',achievement:'Любовь вне орбиты',background:2,total:12,type:'drone'},
    {name:'На другой планете',short:'Планета',goal:'Освободите путь к замку. Победите 8 пришельцев.',intro:'Олег: «Кажется, нас здесь не ждали. Ну ничего, мы ненадолго».',outro:'За воротами кто-то очень не любит счастливые концовки.',achievement:'Мы здесь проездом',background:3,total:8,type:'alien'},
    {name:'Тот, кто мешал свиданию',short:'Босс',goal:'Победите Короля разлуки. Вместе вы сильнее.',intro:'Настя: «Он большой». Олег: «А нас двое».',outro:'Теперь можно просто быть рядом.',achievement:'Любовь победила',background:3,total:1,type:'boss'}
  ];
  class Quest {
    constructor({solo=false,hero=1,random=Math.random}={}){this.solo=solo;this.hero=hero;this.random=random;this.stage=0;this.status='ready';this.events=[];this.time=0;this.begin(0);this.status='ready';}
    begin(stage){this.stage=clamp(stage,0,4);this.level=LEVELS[this.stage];this.status='playing';this.time=0;this.health=12;this.maxHealth=12;this.invincible=0;this.kills=0;this.spawned=0;this.spawnTimer=.5;this.bullets=[];this.enemies=[];this.pickups=[];this.effects=[];this.key=null;this.keyTaken=false;this.events=[];this.portal={x:875,y:330};this.players=[{id:0,x:230,y:355,face:1,attack:0,cooldown:0,dash:0,dashTime:0,invuln:0,moving:false},{id:1,x:310,y:385,face:1,attack:0,cooldown:0,dash:0,dashTime:0,invuln:0,moving:false}];if(this.stage===2){this.players[0].x=180;this.players[0].y=245;this.players[1].x=210;this.players[1].y=375;}this.event('level',this.stage);}
    event(type,value){this.events.push({type,value});}
    takeEvents(){return this.events.splice(0);}
    spawn(){const type=this.level.type,id=this.spawned++,r=this.random;let e={id,type,x:800+r()*90,y:270+r()*180,hp:3,max:3,speed:50+r()*12,phase:'walk',timer:0,cooldown:1+r(),flash:0,face:-1};if(type==='bear')Object.assign(e,{x:730,y:350,hp:34,max:34,speed:58});if(type==='boss')Object.assign(e,{x:740,y:340,hp:62,max:62,speed:46});if(type==='alien')Object.assign(e,{hp:4,max:4,speed:59,x:id%2===0?870:65});if(type==='drone')Object.assign(e,{hp:2,max:2,x:960,y:110+r()*345,speed:75+r()*25});this.enemies.push(e);}
    hurt(amount,target){if(this.invincible>0||target?.invuln>0||this.status!=='playing')return;this.health=Math.max(0,this.health-amount);this.invincible=1.4;this.effects.push({type:'hurt',x:target.x,y:target.y-40,t:.6});this.event('hurt',this.health);if(this.health===0){this.status='dead';this.event('dead');}}
    hit(e,amount,source){if(e.hp<=0)return;e.hp-=amount;e.flash=.15;this.effects.push({type:'hit',x:e.x,y:e.y-35,t:.3});if(source&&e.type!=='drone')e.x=clamp(e.x+(e.x>source.x?1:-1)*9,50,910);if(e.hp<=0){this.kills++;this.event('kill',e.type);this.effects.push({type:'poof',x:e.x,y:e.y-30,t:.65});if(e.type!=='drone'&&(this.kills%2===0||e.type==='bear'))this.pickups.push({x:e.x,y:e.y,type:'heart',t:15});}}
    attack(p){if(p.cooldown>0)return;p.cooldown=this.stage===2?.25:.42;p.attack=.24;this.event('attack',p.id);if(this.stage===2){this.bullets.push({x:p.x+35,y:p.y,vx:500,vy:0,life:2,enemy:false});return;}let hit=false;for(const e of this.enemies){if(e.hp>0&&Math.abs(e.y-p.y)<65&&Math.abs(e.x-p.x)<115){this.hit(e,2,p);p.face=e.x>p.x?1:-1;hit=true;}}if(!hit)this.effects.push({type:'slash',x:p.x+p.face*42,y:p.y-35,t:.2});}
    dash(p,input){if(p.dash>0)return;let dx=input.x||p.face,dy=input.y||0;const len=Math.hypot(dx,dy)||1;p.dash=2.4;p.dashTime=.18;p.invuln=.5;p.dashX=dx/len;p.dashY=dy/len;this.effects.push({type:'dash',x:p.x,y:p.y-20,t:.35});this.event('dash',p.id);}
    autoInput(p){const partner=this.players[this.hero];if(this.stage===2){return {x:(partner.x-70-p.x)*.03,y:(partner.y+75-p.y)*.03,attack:true};}const target=this.enemies.filter(e=>e.hp>0).sort((a,b)=>distance(p,a)-distance(p,b))[0];if(target){const d=distance(p,target);return {x:d>75?(target.x-p.x)/d:0,y:Math.abs(target.y-p.y)>20?(target.y-p.y)/d:0,attack:d<120,dash:false};}return {x:Math.abs(partner.x-65-p.x)>20?Math.sign(partner.x-65-p.x):0,y:Math.abs(partner.y+20-p.y)>20?Math.sign(partner.y+20-p.y):0};}
    update(dt,inputs=[]){if(this.status!=='playing')return;dt=clamp(dt,0,.05);this.time+=dt;this.invincible=Math.max(0,this.invincible-dt);this.spawnTimer-=dt;
      for(let i=0;i<2;i++){const p=this.players[i],raw=this.solo&&i!==this.hero?this.autoInput(p):(inputs[i]||{});let ix=clamp(Number(raw.x)||0,-1,1),iy=clamp(Number(raw.y)||0,-1,1),len=Math.hypot(ix,iy);if(len>1){ix/=len;iy/=len;}p.cooldown=Math.max(0,p.cooldown-dt);p.attack=Math.max(0,p.attack-dt);p.dash=Math.max(0,p.dash-dt);p.invuln=Math.max(0,p.invuln-dt);if(raw.dash)this.dash(p,{x:ix,y:iy});p.moving=Math.abs(ix)+Math.abs(iy)>.05;const speed=this.stage===2?230:180;if(ix)p.face=ix>0?1:-1;if(p.dashTime>0){p.dashTime-=dt;p.x+=p.dashX*590*dt;p.y+=p.dashY*400*dt;}else{p.x+=ix*speed*dt;p.y+=iy*speed*.76*dt;}p.x=clamp(p.x,45,this.stage===2?880:915);p.y=clamp(p.y,this.stage===2?95:255,475);if(raw.attack)this.attack(p);}
      const living=this.enemies.filter(e=>e.hp>0);if(this.spawned<this.level.total&&this.spawnTimer<=0&&living.length<(this.stage===2?4:3)){this.spawn();this.spawnTimer=this.stage===2?1.55:1.9;}
      for(const e of this.enemies){if(e.hp<=0)continue;e.flash=Math.max(0,e.flash-dt);e.cooldown-=dt;const p=this.players.reduce((a,b)=>distance(e,a)<distance(e,b)?a:b),dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;e.face=dx>0?1:-1;
        if(e.type==='drone'){e.x-=e.speed*dt;e.y+=Math.sin(this.time*2+e.id)*18*dt;if(e.cooldown<=0){this.bullets.push({x:e.x-20,y:e.y,vx:-200,vy:0,life:5,enemy:true});e.cooldown=3;}if(e.x<15){e.x=980;e.y=100+this.random()*330;}continue;}
        if(e.phase==='warn'){e.timer-=dt;if(e.timer<=0){e.phase='recover';e.timer=e.type==='boss'?1.25:1;for(const target of this.players){if(distance(target,{x:e.hitX,y:e.hitY})<e.radius)this.hurt(e.type==='boss'?2:1,target);}this.effects.push({type:'impact',x:e.hitX,y:e.hitY,t:.6,r:e.radius});}continue;}
        if(e.phase==='recover'){e.timer-=dt;if(e.timer<=0)e.phase='walk';continue;}
        if(e.type==='alien'&&e.cooldown<=0&&d<440){const norm=Math.hypot(dx,dy)||1;this.bullets.push({x:e.x,y:e.y-15,vx:dx/norm*150,vy:dy/norm*150,life:4,enemy:true});e.cooldown=2.7;}
        if(d<(e.type==='boss'?135:e.type==='bear'?115:72)&&e.cooldown<=0){e.phase='warn';e.timer=e.type==='skeleton'?.75:1.05;e.radius=e.type==='boss'?100:e.type==='bear'?85:54;e.hitX=p.x;e.hitY=p.y;e.cooldown=e.type==='skeleton'?1.8:2.2;}
        else if(d>50){e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*.65*dt;e.y=clamp(e.y,255,475);e.x=clamp(e.x,45,915);}
      }
      for(const b of this.bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.enemy){for(const p of this.players)if(distance({x:p.x,y:p.y-(this.stage===2?0:24)},b)<(this.stage===2?29:24)){this.hurt(1,p);b.life=0;break;}}else{for(const e of this.enemies)if(e.hp>0&&distance(e,b)<42){this.hit(e,1);b.life=0;break;}}}
      this.bullets=this.bullets.filter(b=>b.life>0&&b.x>-30&&b.x<1020&&b.y>-30&&b.y<570);this.enemies=this.enemies.filter(e=>e.hp>0);
      for(const item of this.pickups){item.t-=dt;if(this.players.some(p=>distance(p,item)<55)){this.health=Math.min(this.maxHealth,this.health+2);item.t=0;this.effects.push({type:'heal',x:item.x,y:item.y-30,t:.8});this.event('heal');}}this.pickups=this.pickups.filter(p=>p.t>0);
      this.effects.forEach(e=>e.t-=dt);this.effects=this.effects.filter(e=>e.t>0);
      if(this.status!=='playing')return;
      if(this.kills>=this.level.total){if(this.stage===0){if(!this.key&&!this.keyTaken)this.key={x:710,y:360};if(this.key&&this.players.some(p=>distance(p,this.key)<65)){this.key=null;this.keyTaken=true;this.event('key');}if(this.keyTaken&&this.players.some(p=>distance(p,this.portal)<90))this.finish();}else this.finish();}
    }
    finish(){if(this.status!=='playing')return;this.status=this.stage===4?'win':'clear';this.event(this.status,this.stage);}
    objective(){if(this.stage===0&&this.kills>=this.level.total)return this.keyTaken?'Ключ у нас! К выходу справа →':'Заберите золотой ключ →';return `${this.level.type==='bear'?'Медведь':this.level.type==='boss'?'Король разлуки':'Побеждено'}: ${this.kills} / ${this.level.total}`;}
  }
  return {Quest,LEVELS,W,H};
});
