/* Canvas-приключение. На ПК — два игрока, на телефоне — один и напарник. */
(() => {
  'use strict';
  const {Quest,LEVELS,W,H}=window.LoveQuestCore;
  const rootURL=new URL('./',document.currentScript.src);
  const src=name=>new URL(name,rootURL).href;
  const solo=matchMedia('(pointer:coarse)').matches||matchMedia('(max-width:700px)').matches;
  const keys=new Set(),taps=new Set(),touch=new Set();let dialog,canvas,ctx,model,raf=0,last=0,images=null,callbacks={},priorFocus,hero=1,muted=true,audioContext,paused=false,drawTime=0,lastHud='',assetPromise=null;
  const saveKey='myreallove-quest-v1';
  function readSave(){try{const data=JSON.parse(localStorage.getItem(saveKey));if(data?.version===1&&Number.isInteger(data.stage)&&data.stage>=0&&data.stage<=4)return data;}catch{}return {version:1,stage:0,won:false};}
  function save(stage,won=false){try{localStorage.setItem(saveKey,JSON.stringify({version:1,stage,won}));}catch{}}
  const loadImage=url=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('Не удалось загрузить картинку'));im.src=url;});
  async function characterImage(){let value=getComputedStyle(document.documentElement).getPropertyValue('--character-sheet');if(!value){await new Promise(resolve=>{const observer=new MutationObserver(()=>{if(document.documentElement.classList.contains('characters-ready')){observer.disconnect();resolve();}});observer.observe(document.documentElement,{attributes:true,attributeFilter:['class']});setTimeout(()=>{observer.disconnect();resolve();},5000);});value=getComputedStyle(document.documentElement).getPropertyValue('--character-sheet');}const url=value.trim().replace(/^url\(["']?/, '').replace(/["']?\)$/,'');if(!url)throw new Error('Персонажи ещё загружаются');return loadImage(url);}
  function sliceEnemies(im){const output=[];const cellW=im.width/4,cellH=im.height/2;for(let i=0;i<8;i++){const c=document.createElement('canvas');c.width=cellW;c.height=cellH;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,(i%4)*cellW,Math.floor(i/4)*cellH,cellW,cellH,0,0,cellW,cellH);const data=g.getImageData(0,0,cellW,cellH);let minX=cellW,minY=cellH,maxX=0,maxY=0;for(let y=0;y<cellH;y++)for(let x=0;x<cellW;x++){const k=(y*cellW+x)*4,r=data.data[k],green=data.data[k+1],b=data.data[k+2];if(green>85&&green>r*1.24&&green>b*1.24)data.data[k+3]=0;if(data.data[k+3]>30){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}}g.putImageData(data,0,0);output.push({im:c,x:minX,y:minY,w:Math.max(1,maxX-minX+1),h:Math.max(1,maxY-minY+1)});}return output;}
  async function assets(){if(images)return images;if(!assetPromise)assetPromise=Promise.all([loadImage(src('worlds.webp')),loadImage(src('enemies.webp')),characterImage()]).then(([backgrounds,enemies,characters])=>images={backgrounds,enemies:sliceEnemies(enemies),characters}).catch(error=>{assetPromise=null;throw error;});return assetPromise;}
  function ensureDialog(){if(dialog)return;dialog=document.createElement('dialog');dialog.className='quest-dialog'+(solo?' quest-solo':'');dialog.setAttribute('aria-labelledby','quest-title');dialog.innerHTML=`<div class="quest-top"><div class="quest-brand"><span>♥</span> наше приключение</div><div class="quest-top-actions"><button data-quest-sound aria-pressed="false" aria-label="Включить звук игры">♫ выкл.</button><button data-quest-pause>Пауза</button><button data-quest-close>К истории ↗</button></div></div><div class="quest-map" aria-label="Этапы приключения">${LEVELS.map((l,i)=>`<span data-level="${i}"><i></i>${l.short}</span>`).join('')}</div><div class="quest-view"><canvas width="960" height="540" tabindex="0" aria-label="Игровое поле. Управление указано под игрой."></canvas><div class="quest-hud"><div class="quest-health" role="meter" aria-label="Общее здоровье" aria-valuemin="0" aria-valuemax="12"></div><div class="quest-objective"></div></div><div class="quest-panel"></div></div><div class="quest-controls-info">${solo?'<div><strong>Один игрок + напарник</strong>Двигайся стрелками и удерживай «Удар». Напарник помогает сам.</div>':'<div><strong>ОЛЕГ · игрок 1</strong><kbd>W A S D</kbd> движение · <kbd>F</kbd> удар · <kbd>G</kbd> рывок</div><div><strong>НАСТЯ · игрок 2</strong><kbd>↑ ← ↓ →</kbd> движение · <kbd>Enter</kbd> удар · <kbd>правый Shift</kbd> рывок</div>'}</div><div class="quest-touch"><div class="quest-dpad" aria-label="Направления движения"><button data-control="up" aria-label="Вверх">↑</button><button data-control="left" aria-label="Влево">←</button><button data-control="down" aria-label="Вниз">↓</button><button data-control="right" aria-label="Вправо">→</button></div><div class="quest-touch-actions"><button data-control="dash">Рывок</button><button data-control="attack">Удар</button></div></div><p class="quest-tip">Одно здоровье на двоих. Сердечки лечат. Во время рывка вы неуязвимы.</p><p class="quest-live" role="status" aria-live="polite"></p>`;
    document.body.append(dialog);canvas=dialog.querySelector('canvas');ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
    dialog.querySelector('[data-quest-close]').onclick=close;dialog.querySelector('[data-quest-pause]').onclick=togglePause;dialog.querySelector('[data-quest-sound]').onclick=()=>{muted=!muted;const b=dialog.querySelector('[data-quest-sound]');b.textContent=muted?'♫ выкл.':'♫ вкл.';b.setAttribute('aria-pressed',String(!muted));b.setAttribute('aria-label',muted?'Включить звук игры':'Выключить звук игры');sound('heal');};
    dialog.addEventListener('cancel',e=>{e.preventDefault();if(model?.status==='playing')togglePause();else close();});dialog.addEventListener('close',cleanup);
    dialog.addEventListener('click',e=>{const b=e.target.closest('[data-command]');if(!b)return;const cmd=b.dataset.command;if(cmd==='start')start(0);if(cmd==='continue')start(readSave().stage);if(cmd==='next')start(model.stage+1);if(cmd==='retry')start(model.stage);if(cmd==='resume')togglePause();if(cmd==='close')close();if(cmd==='reload')open(callbacks);if(cmd==='hero'){hero=Number(b.dataset.hero);dialog.querySelectorAll('[data-command=hero]').forEach(el=>el.setAttribute('aria-pressed',String(Number(el.dataset.hero)===hero)));}});
    for(const b of dialog.querySelectorAll('[data-control]')){b.addEventListener('pointerdown',e=>{if(model?.status!=='playing'||paused)return;e.preventDefault();b.setPointerCapture(e.pointerId);touch.add(b.dataset.control);b.classList.add('active');});const release=()=>{touch.delete(b.dataset.control);b.classList.remove('active');};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);}
  }
  function panel(title,text,buttons,kicker='НАШЕ МАЛЕНЬКОЕ ПРИКЛЮЧЕНИЕ',extra=''){const p=dialog.querySelector('.quest-panel');p.hidden=false;p.classList.remove('quest-win');p.innerHTML=`<span class="quest-kicker">${kicker}</span><h2 id="quest-title">${title}</h2><p>${text}</p>${extra}<div class="quest-panel-actions">${buttons}</div>`;}
  const button=(label,cmd,primary=true)=>`<button class="${primary?'primary':'quest-secondary'}" data-command="${cmd}">${label}</button>`;
  async function open(options={}){callbacks=options;ensureDialog();if(!dialog.open){priorFocus=document.activeElement;dialog.showModal();}document.body.classList.add('quest-open');keys.clear();taps.clear();touch.clear();paused=false;panel('Собираемся в приключение…','Сейчас появятся наши герои.','');try{await assets();if(!dialog.open)return;model=new Quest({solo,hero});const progress=readSave();panel('Вместе —<br>через что угодно.',solo?'Выбери героя. Второй будет прикрывать тебя.':'Зовите друг друга к клавиатуре. Олег — WASD, Настя — стрелки.',(progress.stage>0?button('Продолжить · '+LEVELS[progress.stage].short,'continue'):'')+button(progress.stage>0?'С самого начала':'Начать приключение','start',progress.stage===0),'ПЯТЬ МАЛЕНЬКИХ ПРИКЛЮЧЕНИЙ · ОДНА ЛЮБОВЬ',solo?`<div class="quest-character-choice"><button data-command="hero" data-hero="1" aria-pressed="${hero===1}">Настя</button><button data-command="hero" data-hero="0" aria-pressed="${hero===0}">Олег</button></div>`:'');last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(frame);updateHud();}catch{panel('Картинки задержались','Проверь соединение и попробуй ещё раз.',button('Загрузить снова','reload')+button('К истории','close',false));}}
  function start(stage){model=new Quest({solo,hero});model.begin(stage);model.takeEvents();paused=false;keys.clear();taps.clear();touch.clear();last=performance.now();save(stage);dialog.querySelector('.quest-panel').hidden=true;dialog.querySelector('[data-quest-pause]').textContent='Пауза';canvas.focus({preventScroll:true});say(LEVELS[stage].intro);updateHud();sound('level');}
  function say(text){dialog.querySelector('.quest-live').textContent=text;dialog.querySelector('.quest-tip').textContent=text;}
  function togglePause(){if(model?.status!=='playing')return;paused=!paused;keys.clear();taps.clear();touch.clear();dialog.querySelector('[data-quest-pause]').textContent=paused?'Продолжить':'Пауза';if(paused)panel('Никуда не спешим.','Выдохните. Приключение вас подождёт.',button('Продолжить','resume'),'ПАУЗА');else{dialog.querySelector('.quest-panel').hidden=true;last=performance.now();canvas.focus({preventScroll:true});}}
  function cleanup(){cancelAnimationFrame(raf);keys.clear();taps.clear();touch.clear();document.body.classList.remove('quest-open');dialog.querySelectorAll('[data-control]').forEach(b=>b.classList.remove('active'));const win=dialog.querySelector('.quest-win img');if(win)win.remove();callbacks.onClose?.();priorFocus?.focus({preventScroll:true});}
  function close(){if(dialog?.open)dialog.close();}
  const codes=['KeyW','KeyA','KeyS','KeyD','KeyF','KeyG','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter','ShiftRight','KeyP'];
  addEventListener('keydown',e=>{if(!dialog?.open||!codes.includes(e.code))return;if(model?.status!=='playing'||(paused&&e.code!=='KeyP'))return;e.preventDefault();e.stopPropagation();if(e.code==='KeyP'){if(!e.repeat)togglePause();return;}if(!paused){keys.add(e.code);taps.add(e.code);}},true);
  addEventListener('keyup',e=>{keys.delete(e.code);if(dialog?.open&&codes.includes(e.code)){e.preventDefault();e.stopPropagation();}},true);
  addEventListener('blur',()=>{keys.clear();taps.clear();touch.clear();if(dialog?.open&&model?.status==='playing'&&!paused)togglePause();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&dialog?.open&&model?.status==='playing'&&!paused)togglePause();});
  function inputs(){const pressed=code=>keys.has(code)||taps.has(code);const p0={x:Number(pressed('KeyD'))-Number(pressed('KeyA')),y:Number(pressed('KeyS'))-Number(pressed('KeyW')),attack:pressed('KeyF'),dash:pressed('KeyG')},p1={x:Number(pressed('ArrowRight'))-Number(pressed('ArrowLeft')),y:Number(pressed('ArrowDown'))-Number(pressed('ArrowUp')),attack:pressed('Enter'),dash:pressed('ShiftRight')};const all=[p0,p1];if(solo)all[hero]={x:Number(touch.has('right'))-Number(touch.has('left')),y:Number(touch.has('down'))-Number(touch.has('up')),attack:touch.has('attack'),dash:touch.has('dash')};return all;}
  function updateHud(){const key=[model.stage,model.health,model.kills,model.keyTaken,model.status].join();if(key===lastHud)return;lastHud=key;const h=dialog.querySelector('.quest-health');h.textContent='♥'.repeat(model.health)+'♡'.repeat(model.maxHealth-model.health);h.setAttribute('aria-valuenow',String(model.health));h.setAttribute('aria-valuetext',`${model.health} из 12`);dialog.querySelector('.quest-objective').textContent=model.objective();dialog.querySelectorAll('[data-level]').forEach(el=>{const i=Number(el.dataset.level);el.classList.toggle('current',i===model.stage);el.classList.toggle('done',i<model.stage);});dialog.querySelector('[data-control=attack]').textContent=model.stage===2?'Огонь':'Удар';}
  function onEvents(){for(const e of model.takeEvents()){if(['attack','hurt','heal','level','dash','kill','key'].includes(e.type))sound(e.type);if(e.type==='key')say('Настя: «Ключ наш! Скорее к выходу справа!»');if(e.type==='clear'){save(model.stage+1);callbacks.onAchievement?.(model.level.achievement,'Ещё один этап. Вместе.','♥');panel('Получилось.<br>Мы справились.',model.level.outro,button(model.stage===1?'Пуф! В космос →':'Дальше, вместе →','next'),model.level.achievement.toUpperCase());sound('level');}if(e.type==='dead')panel('Ещё одна попытка.<br>Вместе получится.','Продолжим с этого этапа, с полным здоровьем.',button('Попробовать ещё','retry'),'НИЧЕГО СТРАШНОГО');if(e.type==='win'){save(4,true);callbacks.onAchievement?.('Любовь победила','Любое приключение — вместе.','♥');const p=dialog.querySelector('.quest-panel');p.hidden=false;p.classList.add('quest-win');p.innerHTML=`<img src="${src('happy-ending.gif')}" alt="Олег и Настя прыгают по цветочному полю, обнимаются и целуются"><span class="quest-kicker">ПРИКЛЮЧЕНИЕ ПРОЙДЕНО</span><h2 id="quest-title">Мой любимый напарник.<br>В игре. И в жизни.</h2><div class="quest-panel-actions">${button('Вернуться к нашей истории ♡','close')}</div>`;sound('level');}}}
  function sound(type){if(muted)return;try{audioContext ||=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const notes=type==='level'?[523,659,784,1047]:type==='heal'?[659,880]:type==='hurt'?[170,120]:type==='attack'?[350]:type==='kill'?[500,700]:[450];notes.forEach((freq,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain(),t=audioContext.currentTime+i*.075;o.type='triangle';o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.022,t);g.gain.exponentialRampToValueAtTime(.001,t+.13);o.connect(g);g.connect(audioContext.destination);o.start(t);o.stop(t+.14);});}catch{muted=true;}}
  function frame(t){if(!dialog.open)return;const dt=Math.min((t-last)/1000,.05);last=t;if(model&&images){if(!paused){model.update(dt,inputs());taps.clear();}drawTime=t/1000;draw();onEvents();updateHud();}raf=requestAnimationFrame(frame);}
  function text(value,x,y,size=16,color='#ffdeec',align='center'){ctx.save();ctx.font=`${size}px 'Courier New',monospace`;ctx.textAlign=align;ctx.fillStyle='#170e24';ctx.fillText(value,x+1,y+2);ctx.fillStyle=color;ctx.fillText(value,x,y);ctx.restore();}
  function heart(x,y,size=10,color='#f8a8cd'){ctx.save();ctx.fillStyle=color;const map=['01100110','11111111','11111111','01111110','00111100','00011000'];const unit=size/8;map.forEach((row,j)=>[...row].forEach((v,i)=>{if(v==='1')ctx.fillRect(Math.round(x+(i-4)*unit),Math.round(y+j*unit),Math.ceil(unit),Math.ceil(unit));}));ctx.restore();}
  function shadow(x,y,size=28){ctx.fillStyle='#16081f65';ctx.beginPath();ctx.ellipse(x,y,size,size*.23,0,0,7);ctx.fill();}
  function heroSprite(p,small=false){const height=small?54:116,width=height*.84,im=images.characters,cw=im.width/4,ch=im.height/3,frame=p.moving?Math.floor(drawTime*9)%4:0,row=p.id===0?2:1;ctx.save();ctx.translate(Math.round(p.x),Math.round(p.y));if(model.invincible>0&&Math.floor(drawTime*12)%2===0)ctx.globalAlpha=.5;ctx.scale(p.face,1);ctx.drawImage(im,frame*cw,row*ch,cw,ch,-width/2,-height,width,height);if(!small&&p.attack>0){ctx.strokeStyle=p.id===0?'#ffdbb2':'#ff9ccd';ctx.lineWidth=5;ctx.beginPath();ctx.arc(32,-51,46,-1.2,1.15);ctx.stroke();for(let n=0;n<3;n++)heart(48+n*12,-65+n*12,8,'#ffb9d7');}ctx.restore();if(!small){text(p.id===0?'ОЛЕГ':'НАСТЯ',p.x,p.y-110,12,p.id===0?'#fff0c5':'#ffc9e0');if(p.dash<=0){ctx.fillStyle='#ffb8d680';ctx.fillRect(p.x-13,p.y+10,26,2);}}}
  function ufo(x,y,id=0,enemy=false){shadow(x,y+25,34);ctx.save();ctx.translate(Math.round(x),Math.round(y));if(enemy){ctx.fillStyle='#65416f';ctx.fillRect(-27,-7,54,17);ctx.fillStyle='#ef7a9b';ctx.fillRect(-16,-16,32,17);ctx.fillStyle='#ffcabb';ctx.fillRect(-32,1,64,6);ctx.fillStyle='#42283e';ctx.fillRect(-7,-12,14,8);}else{ctx.fillStyle='#78638b';ctx.fillRect(-41,0,82,12);ctx.fillStyle='#e8c2dd';ctx.fillRect(-33,-5,66,14);ctx.fillStyle='#be83b6';ctx.fillRect(-25,12,50,5);ctx.fillStyle='#97d8dc85';ctx.beginPath();ctx.ellipse(0,-8,28,25,Math.PI,0,Math.PI);ctx.fill();const pp={id,x:0,y:3,face:1,moving:false};heroSprite(pp,true);ctx.fillStyle='#e4bddf';ctx.fillRect(-41,4,82,7);for(let i=-2;i<=2;i++){ctx.fillStyle=i%2===Math.floor(drawTime*4)%2?'#ffc1e0':'#bb8bd4';ctx.fillRect(i*13-3,8,6,4);}ctx.fillStyle='#ffb8d8';ctx.fillRect(-46-Math.floor(Math.sin(drawTime*20)*6),5,11,4);}ctx.restore();if(!enemy)text(id===0?'ОЛЕГ':'НАСТЯ',x,y-42,12);}
  function enemySprite(e){const row={skeleton:0,bear:2,alien:4,boss:6}[e.type],index=row+(e.phase==='warn'||e.phase==='recover'?1:0),s=images.enemies[index];const height=e.type==='boss'?172:e.type==='bear'?130:100,width=s.w/s.h*height;shadow(e.x,e.y,width*.32);ctx.save();ctx.translate(Math.round(e.x),Math.round(e.y));ctx.scale(-e.face,1);if(e.flash>0)ctx.globalAlpha=.45;const bob=e.phase==='walk'?Math.sin(drawTime*7+e.id)*2:0;ctx.drawImage(s.im,s.x,s.y,s.w,s.h,-width/2,-height+bob,width,height);ctx.restore();if(e.type==='boss'||e.type==='bear'){const barW=e.type==='boss'?150:110;ctx.fillStyle='#170a24';ctx.fillRect(e.x-barW/2-2,e.y-height-16,barW+4,8);ctx.fillStyle='#e697b8';ctx.fillRect(e.x-barW/2,e.y-height-14,barW*e.hp/e.max,4);}}
  function draw(){ctx.clearRect(0,0,W,H);const bg=images.backgrounds,idx=model.level.background,bw=bg.width/2,bh=bg.height/2;ctx.drawImage(bg,(idx%2)*bw,Math.floor(idx/2)*bh,bw,bh,0,0,W,H);ctx.fillStyle=model.stage===4?'#270d333d':'#1b102219';ctx.fillRect(0,0,W,H);
    for(let i=0;i<24;i++){const x=(i*137+drawTime*(model.stage===2?-12:2)+W*100)%W,y=70+(i*83)%440;ctx.fillStyle=i%2?'#ffbcdb60':'#c7bbdf50';ctx.fillRect(x,y+Math.sin(drawTime+i)*7,2,2);}
    if(model.stage===0&&model.keyTaken){const p=model.portal;ctx.fillStyle='#bb74b445';ctx.fillRect(p.x-28,p.y-118,56,123);ctx.strokeStyle='#efb6d5';ctx.lineWidth=3;ctx.strokeRect(p.x-28,p.y-118,56,123);text('ВЫХОД',p.x,p.y-131,13);heart(p.x,p.y-70,24);}
    for(const e of model.enemies)if(e.phase==='warn'){ctx.fillStyle='#ed72724a';ctx.strokeStyle='#ff9eae';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(e.hitX,e.hitY,e.radius,e.radius*.5,0,0,Math.PI*2);ctx.fill();ctx.stroke();text('!',e.hitX,e.hitY-10,24,'#ffe2a8');}
    for(const item of model.pickups){shadow(item.x,item.y,12);heart(item.x,item.y-20+Math.sin(drawTime*4)*5,22);}
    if(model.key){const {x,y}=model.key;shadow(x,y,18);ctx.strokeStyle='#ffe095';ctx.lineWidth=7;ctx.beginPath();ctx.arc(x-10,y-27+Math.sin(drawTime*3)*5,10,0,Math.PI*2);ctx.moveTo(x,y-27);ctx.lineTo(x+24,y-27);ctx.lineTo(x+24,y-18);ctx.moveTo(x+15,y-27);ctx.lineTo(x+15,y-20);ctx.stroke();text('КЛЮЧ',x,y-53,13,'#ffe6a8');}
    if(model.stage===2){for(const e of model.enemies)ufo(e.x,e.y,0,true);for(const p of model.players)ufo(p.x,p.y,p.id);}else{const entities=[...model.players.map(p=>({p,y:p.y})),...model.enemies.map(e=>({e,y:e.y}))].sort((a,b)=>a.y-b.y);for(const item of entities)if(item.p){shadow(item.p.x,item.p.y,24);heroSprite(item.p);}else enemySprite(item.e);}
    for(const b of model.bullets){if(b.enemy){ctx.fillStyle='#ff9f7d';ctx.fillRect(b.x-5,b.y-4,11,8);}else heart(b.x,b.y-5,15);}
    for(const e of model.effects){ctx.save();ctx.globalAlpha=Math.min(1,e.t*3);if(e.type==='hit'||e.type==='poof'){for(let i=0;i<7;i++){const a=i*Math.PI*2/7,spread=(.7-e.t)*75;ctx.fillStyle=i%2?'#fac1d7':'#eedabe';ctx.fillRect(e.x+Math.cos(a)*spread,e.y+Math.sin(a)*spread,5,5);}}else if(e.type==='heal')text('+2 ♥',e.x,e.y-20,20,'#e9e5be');else if(e.type==='impact'){ctx.strokeStyle='#ffadc9';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(e.x,e.y,(e.r||65)*(1-e.t),25,0,0,7);ctx.stroke();}else if(e.type==='dash'){ctx.fillStyle='#eed4f555';ctx.fillRect(e.x-30,e.y-25,65,4);}ctx.restore();}
    if(model.status==='playing'&&model.time<5){ctx.fillStyle='#1d1024ba';ctx.fillRect(190,475,580,36);text(model.level.goal,480,498,13);}
  }
  window.LoveQuest={open,close,get active(){return Boolean(dialog?.open);}};
})();
